### ISSUE TITLE
Character Select System

### ISSUE THREAD

**Issue by TabiasP** [TabiasP/Prometheus#19]
One of the biggest problems we're having so far, is finding the most efficient way to creating a character select system. As of current, when implementing this feature we must create an object of each character class along with all of it's attributes. For example:

while(true){
if(choice == 1){
Character_Warrior character = new Character_Warrior();
character.setHealth(34);
character.setDefense(23);
}
else if(choice == 2){
Character_Elf character = new Character_Elf();
character.setHealth(34);
character.setDefense(23);
}

As you can see, this is just a small example, but we have a total of 5 character, and many more attributes to select from. I am looking for some assistance on what best way you think we should approach this problem? 

}

**Comment by madisonkh** [comment]
I've already started to rewrite the character selection. It now makes it so that when you begin the game session and choose your character, it creates a single character object based on the class you chose (the individual classes now extend the base character class), thus making it unnecessary to use the set methods (the default beginning values for each attribute are created automatically through the constructor for each individual class). This single character instance can then be passed around through the different modes, and no other instances would have to be created.

Example, in the Main_Class:
if(response == 1) {
     System.out.println("You have chosen to be a warrior!");
     Character_Warrior character = new Character_Warrior();
}

then the constructor for Character_Warrior looks like:

public class Character_Warrior extends Character_Class {
	
		public Character_Warrior() {
			super.name = "Warrior";
			super.health = 100;
			super.damage = 50;
			super.magic = 20;
			super.defense = 50;
			super.boost = 50;
			super.weapon_damage = 60;
			super.armor = 50;
			super.intelligence = 50;
			super.speed = 70;
			super.strength = 60;
			super.resistance = 60;
		}
}

If someone has a more efficient way to do this, or if I'm missing where all this other stuff absolutely has to happen, please correct me.

**Comment by TabiasP** [comment]
@madisonkh How about we make a separate class called "Character_Select" and sets up a method that passes an object. For example:

if(response == 1) {
     System.out.println("You have chosen to be a warrior!");
     Character_Warrior character = new Character_Warrior();

public static void character_select(Object a){
a.setHealth();
a.setDefense();
}

This way, we would only need to do it once? but i'm not sure if this works or not; I haven't checked myself.

**Comment by madisonkh** [comment]
Having a character selection class isn't necessarily a bad idea, though it might be unnecessary. Mostly because I still fail to see why we need to set each of the class attributed through set methods if the constructor can set default values by itself upon creation.

**Comment by TabiasP** [comment]
Because from my understanding, if we want to display the stats, we need to put those values in a variable somewhere. Like we want information regarding the health, damage, etc. We then need to display the stats on screen. Maybe I'm thinking the wrong way, but thats the way the battle system is working so far. Have a look at the battle system class.

**Comment by madisonkh** [comment]
Oh okay, If you're worried about displaying stata, then how about a method in the character class that returns to stats in the form of a string after character creation? It could also be used later to display stats between battles or upon returning to the mode select. During a battle, when the player needs an update on their health or anything like that during the battles, something similar could be done for relevant stats, though current health is saved in the battle system class rather than the character class

**Comment by oscarmartinez0880** [comment]
I actually put that in the readme, I think the stats of all the characters should be displayed before you select one, and then again after an upgrade or health boost.
